# Generated by Django 6.0.4 on 2026-09-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0007_add_weekly_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='stamp',
            field=models.ImageField(blank=True, help_text="To'lov kvitansiyalarida ko'rinadigan muhr/pechat rasmi", null=True, upload_to='academy_stamps/'),
        ),
    ]
