# Generated by Django 6.0.4 on 2026-09-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0007_add_weekly_report_time'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tuitiontemplate',
            unique_together={('academy', 'category', 'name')},
        ),
    ]
