# Generated by Django 6.0.4 on 2026-09-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_enrollments(apps, schema_editor):
    # Existing GroupMembership rows predate this model/its signals, so they
    # never triggered the post_save handler that creates an Enrollment —
    # do it once here for every membership that doesn't have one yet.
    GroupMembership = apps.get_model('groups', 'GroupMembership')
    Enrollment = apps.get_model('payments', 'Enrollment')

    already = set(Enrollment.objects.values_list('student_id', 'group_id'))
    to_create = [
        Enrollment(student_id=m.student_id, group_id=m.group_id, started_at=m.joined_at)
        for m in GroupMembership.objects.all()
        if (m.student_id, m.group_id) not in already
    ]
    Enrollment.objects.bulk_create(to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_lesson_ended_at'),
        ('payments', '0002_alter_tuitiontemplate_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_enrollments', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'group'], name='payments_en_student_4e3c8e_idx')],
            },
        ),
        migrations.RunPython(backfill_enrollments, migrations.RunPython.noop),
    ]
