# Generated by Django 6.0.4 on 2026-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('score', 'Score Added'), ('absent', 'Marked Absent'), ('lesson', 'New Lesson'), ('announcement', 'Announcement'), ('exam', 'Exam Result'), ('payment', 'Payment Reminder')], max_length=20),
        ),
    ]
